package whatisnewin.javax.security.auth.kerberos;

import javax.security.auth.kerberos.KerberosPrincipal;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link KerberosPrincipal}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link KerberosPrincipal} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see KerberosPrincipal
 */
public final class WhatIsNewInKerberosPrincipal
{
  /**
   * Example usage of the new field {@link KerberosPrincipal#KRB_NT_ENTERPRISE}.
   * @since 13
   * @see KerberosPrincipal#KRB_NT_ENTERPRISE
   */
  public static final int KRB_NT_ENTERPRISE = KerberosPrincipal.KRB_NT_ENTERPRISE;

}
