package whatisnewin.java.lang;

import java.lang.Character.UnicodeScript;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link UnicodeScript}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link UnicodeScript} is an old class but has new fields, constructors or methods.
 * @since 1.7
 * @see UnicodeScript
 */
public final class WhatIsNewInCharacter$UnicodeScript
{
  /**
   * Example usage of the new field {@link UnicodeScript#ELYMAIC}.
   * @since 13
   * @see UnicodeScript#ELYMAIC
   */
  public static final UnicodeScript ELYMAIC = UnicodeScript.ELYMAIC;

  /**
   * Example usage of the new field {@link UnicodeScript#NANDINAGARI}.
   * @since 13
   * @see UnicodeScript#NANDINAGARI
   */
  public static final UnicodeScript NANDINAGARI = UnicodeScript.NANDINAGARI;

  /**
   * Example usage of the new field {@link UnicodeScript#NYIAKENG_PUACHUE_HMONG}.
   * @since 13
   * @see UnicodeScript#NYIAKENG_PUACHUE_HMONG
   */
  public static final UnicodeScript NYIAKENG_PUACHUE_HMONG = UnicodeScript.NYIAKENG_PUACHUE_HMONG;

  /**
   * Example usage of the new field {@link UnicodeScript#WANCHO}.
   * @since 13
   * @see UnicodeScript#WANCHO
   */
  public static final UnicodeScript WANCHO = UnicodeScript.WANCHO;

}
