package whatisnewin.java.lang;

import java.lang.Character.UnicodeBlock;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link UnicodeBlock}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link UnicodeBlock} is an old class but has new fields, constructors or methods
 * @since 1.2
 * @see UnicodeBlock
 */
public final class WhatIsNewInCharacter$UnicodeBlock
{
  /**
   * Example usage of the new field {@link UnicodeBlock#ELYMAIC}
   * @since 13
   * @see UnicodeBlock#ELYMAIC
   */
  public static  final UnicodeBlock ELYMAIC = UnicodeBlock.ELYMAIC;

  /**
   * Example usage of the new field {@link UnicodeBlock#NANDINAGARI}
   * @since 13
   * @see UnicodeBlock#NANDINAGARI
   */
  public static  final UnicodeBlock NANDINAGARI = UnicodeBlock.NANDINAGARI;

  /**
   * Example usage of the new field {@link UnicodeBlock#TAMIL_SUPPLEMENT}
   * @since 13
   * @see UnicodeBlock#TAMIL_SUPPLEMENT
   */
  public static  final UnicodeBlock TAMIL_SUPPLEMENT = UnicodeBlock.TAMIL_SUPPLEMENT;

  /**
   * Example usage of the new field {@link UnicodeBlock#EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS}
   * @since 13
   * @see UnicodeBlock#EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS
   */
  public static  final UnicodeBlock EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS = UnicodeBlock.EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS;

  /**
   * Example usage of the new field {@link UnicodeBlock#SMALL_KANA_EXTENSION}
   * @since 13
   * @see UnicodeBlock#SMALL_KANA_EXTENSION
   */
  public static  final UnicodeBlock SMALL_KANA_EXTENSION = UnicodeBlock.SMALL_KANA_EXTENSION;

  /**
   * Example usage of the new field {@link UnicodeBlock#NYIAKENG_PUACHUE_HMONG}
   * @since 13
   * @see UnicodeBlock#NYIAKENG_PUACHUE_HMONG
   */
  public static  final UnicodeBlock NYIAKENG_PUACHUE_HMONG = UnicodeBlock.NYIAKENG_PUACHUE_HMONG;

  /**
   * Example usage of the new field {@link UnicodeBlock#WANCHO}
   * @since 13
   * @see UnicodeBlock#WANCHO
   */
  public static  final UnicodeBlock WANCHO = UnicodeBlock.WANCHO;

  /**
   * Example usage of the new field {@link UnicodeBlock#OTTOMAN_SIYAQ_NUMBERS}
   * @since 13
   * @see UnicodeBlock#OTTOMAN_SIYAQ_NUMBERS
   */
  public static  final UnicodeBlock OTTOMAN_SIYAQ_NUMBERS = UnicodeBlock.OTTOMAN_SIYAQ_NUMBERS;

  /**
   * Example usage of the new field {@link UnicodeBlock#SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A}
   * @since 13
   * @see UnicodeBlock#SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A
   */
  public static  final UnicodeBlock SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A = UnicodeBlock.SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A;

}
