package whatisnewin.java.lang;


/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link String}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link String} is an old class but has new fields, constructors or methods.
 * @since 1.0
 * @see String
 */
public final class WhatIsNewInString
{
  /**
   * Example call to new method {@link String#formatted(Object[])}.
   * @since 13
   * @see String#formatted(Object[])
   */
  public String formatted(Object[] args)
  {
    String testee = $$$();

    String result = testee.formatted(args);
    return result;
  }

  /**
   * Example call to new method {@link String#stripIndent()}.
   * @since 13
   * @see String#stripIndent()
   */
  public String stripIndent()
  {
    String testee = $$$();

    String result = testee.stripIndent();
    return result;
  }

  /**
   * Example call to new method {@link String#translateEscapes()}.
   * @since 13
   * @see String#translateEscapes()
   */
  public String translateEscapes()
  {
    String testee = $$$();

    String result = testee.translateEscapes();
    return result;
  }

  private String $$$()
  {
    return null;
  }
}
