package whatisnewin.java.nio;

import java.nio.Buffer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Buffer}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link Buffer} is an old class but has new fields, constructors or methods
 * @since 1.4
 * @see Buffer
 */
public final class WhatIsNewInBuffer
{
  /**
   * Example call to new method {@link Buffer#slice}
   * @since 13
   * @see Buffer#slice
   */
  public Buffer slice(int index, int length)
  {
    Buffer testee = $$$();

    Buffer result = testee.slice(index, length);
    return result;
  }

  private Buffer $$$()
  {
    return null;
  }
}
