package whatisnewin.java.nio;

import java.nio.CharBuffer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link CharBuffer}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link CharBuffer} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see CharBuffer
 */
public final class WhatIsNewInCharBuffer
{
  /**
   * Example call to new method {@link CharBuffer#slice(int, int)}.
   * @since 13
   * @see CharBuffer#slice(int, int)
   */
  public CharBuffer slice(int index, int length)
  {
    CharBuffer testee = $$$();

    CharBuffer result = testee.slice(index, length);
    return result;
  }

  /**
   * Example call to new method {@link CharBuffer#get(int, char[], int, int)}.
   * @since 13
   * @see CharBuffer#get(int, char[], int, int)
   */
  public CharBuffer get(int index, char[] dst, int offset, int length)
  {
    CharBuffer testee = $$$();

    CharBuffer result = testee.get(index, dst, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link CharBuffer#get(int, char[])}.
   * @since 13
   * @see CharBuffer#get(int, char[])
   */
  public CharBuffer get(int index, char[] dst)
  {
    CharBuffer testee = $$$();

    CharBuffer result = testee.get(index, dst);
    return result;
  }

  /**
   * Example call to new method {@link CharBuffer#put(int, char[], int, int)}.
   * @since 13
   * @see CharBuffer#put(int, char[], int, int)
   */
  public CharBuffer put(int index, char[] src, int offset, int length)
  {
    CharBuffer testee = $$$();

    CharBuffer result = testee.put(index, src, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link CharBuffer#put(int, char[])}.
   * @since 13
   * @see CharBuffer#put(int, char[])
   */
  public CharBuffer put(int index, char[] src)
  {
    CharBuffer testee = $$$();

    CharBuffer result = testee.put(index, src);
    return result;
  }

  private CharBuffer $$$()
  {
    return null;
  }
}
