package whatisnewin.java.nio;

import java.nio.IntBuffer;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link IntBuffer}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link IntBuffer} is an old class but has new fields, constructors or methods
 * @since 1.4
 * @see IntBuffer
 */
public final class WhatIsNewInIntBuffer
{
  /**
   * Example call to new method {@link IntBuffer#slice}
   * @since 13
   * @see IntBuffer#slice
   */
  public IntBuffer slice(int index, int length)
  {
    IntBuffer testee = $$$();

    IntBuffer result = testee.slice(index, length);
    return result;
  }

  /**
   * Example call to new method {@link IntBuffer#get}
   * @since 13
   * @see IntBuffer#get
   */
  public IntBuffer get(int index, int[] dst, int offset, int length)
  {
    IntBuffer testee = $$$();

    IntBuffer result = testee.get(index, dst, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link IntBuffer#get}
   * @since 13
   * @see IntBuffer#get
   */
  public IntBuffer get(int index, int[] dst)
  {
    IntBuffer testee = $$$();

    IntBuffer result = testee.get(index, dst);
    return result;
  }

  /**
   * Example call to new method {@link IntBuffer#put}
   * @since 13
   * @see IntBuffer#put
   */
  public IntBuffer put(int index, int[] src, int offset, int length)
  {
    IntBuffer testee = $$$();

    IntBuffer result = testee.put(index, src, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link IntBuffer#put}
   * @since 13
   * @see IntBuffer#put
   */
  public IntBuffer put(int index, int[] src)
  {
    IntBuffer testee = $$$();

    IntBuffer result = testee.put(index, src);
    return result;
  }

  private IntBuffer $$$()
  {
    return null;
  }
}
