package whatisnewin.java.nio;

import java.nio.LongBuffer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link LongBuffer}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link LongBuffer} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see LongBuffer
 */
public final class WhatIsNewInLongBuffer
{
  /**
   * Example call to new method {@link LongBuffer#put(int, long[], int, int)}.
   * @since 13
   * @see LongBuffer#put(int, long[], int, int)
   */
  public LongBuffer put(int index, long[] src, int offset, int length)
  {
    LongBuffer testee = $$$();

    LongBuffer result = testee.put(index, src, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link LongBuffer#put(int, long[])}.
   * @since 13
   * @see LongBuffer#put(int, long[])
   */
  public LongBuffer put(int index, long[] src)
  {
    LongBuffer testee = $$$();

    LongBuffer result = testee.put(index, src);
    return result;
  }

  /**
   * Example call to new method {@link LongBuffer#get(int, long[], int, int)}.
   * @since 13
   * @see LongBuffer#get(int, long[], int, int)
   */
  public LongBuffer get(int index, long[] dst, int offset, int length)
  {
    LongBuffer testee = $$$();

    LongBuffer result = testee.get(index, dst, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link LongBuffer#get(int, long[])}.
   * @since 13
   * @see LongBuffer#get(int, long[])
   */
  public LongBuffer get(int index, long[] dst)
  {
    LongBuffer testee = $$$();

    LongBuffer result = testee.get(index, dst);
    return result;
  }

  /**
   * Example call to new method {@link LongBuffer#slice(int, int)}.
   * @since 13
   * @see LongBuffer#slice(int, int)
   */
  public LongBuffer slice(int index, int length)
  {
    LongBuffer testee = $$$();

    LongBuffer result = testee.slice(index, length);
    return result;
  }

  private LongBuffer $$$()
  {
    return null;
  }
}
