package whatisnewin.java.nio;

import java.nio.ShortBuffer;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ShortBuffer}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link ShortBuffer} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see ShortBuffer
 */
public final class WhatIsNewInShortBuffer
{
  /**
   * Example call to new method {@link ShortBuffer#slice(int, int)}.
   * @since 13
   * @see ShortBuffer#slice(int, int)
   */
  public ShortBuffer slice(int index, int length)
  {
    ShortBuffer testee = $$$();

    ShortBuffer result = testee.slice(index, length);
    return result;
  }

  /**
   * Example call to new method {@link ShortBuffer#get(int, short[], int, int)}.
   * @since 13
   * @see ShortBuffer#get(int, short[], int, int)
   */
  public ShortBuffer get(int index, short[] dst, int offset, int length)
  {
    ShortBuffer testee = $$$();

    ShortBuffer result = testee.get(index, dst, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link ShortBuffer#get(int, short[])}.
   * @since 13
   * @see ShortBuffer#get(int, short[])
   */
  public ShortBuffer get(int index, short[] dst)
  {
    ShortBuffer testee = $$$();

    ShortBuffer result = testee.get(index, dst);
    return result;
  }

  /**
   * Example call to new method {@link ShortBuffer#put(int, short[], int, int)}.
   * @since 13
   * @see ShortBuffer#put(int, short[], int, int)
   */
  public ShortBuffer put(int index, short[] src, int offset, int length)
  {
    ShortBuffer testee = $$$();

    ShortBuffer result = testee.put(index, src, offset, length);
    return result;
  }

  /**
   * Example call to new method {@link ShortBuffer#put(int, short[])}.
   * @since 13
   * @see ShortBuffer#put(int, short[])
   */
  public ShortBuffer put(int index, short[] src)
  {
    ShortBuffer testee = $$$();

    ShortBuffer result = testee.put(index, src);
    return result;
  }

  private ShortBuffer $$$()
  {
    return null;
  }
}
