package whatisnewin.javax.annotation.processing;

import javax.annotation.processing.ProcessingEnvironment;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link ProcessingEnvironment}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link ProcessingEnvironment} is an old class but has new fields, constructors or methods.
 * @since 1.6
 * @see ProcessingEnvironment
 */
public final class WhatIsNewInProcessingEnvironment
{
  /**
   * Example call to new method {@link ProcessingEnvironment#isPreviewEnabled()}.
   * @since 13
   * @see ProcessingEnvironment#isPreviewEnabled()
   */
  public boolean isPreviewEnabled()
  {
    ProcessingEnvironment testee = $$$();

    boolean result = testee.isPreviewEnabled();
    return result;
  }

  private ProcessingEnvironment $$$()
  {
    return null;
  }
}
