package whatisnewin.javax.tools;

import javax.tools.StandardJavaFileManager;
import javax.tools.JavaFileObject;
import java.util.Collection;
import java.nio.file.Path;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link StandardJavaFileManager}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link StandardJavaFileManager} is an old class but has new fields, constructors or methods
 * @since 1.6
 * @see StandardJavaFileManager
 */
public final class WhatIsNewInStandardJavaFileManager
{
  /**
   * Example call to new method {@link StandardJavaFileManager#getJavaFileObjectsFromPaths}
   * @since 13
   * @see StandardJavaFileManager#getJavaFileObjectsFromPaths
   */
  public Iterable<? extends JavaFileObject> getJavaFileObjectsFromPaths(Collection<? extends Path> paths)
  {
    StandardJavaFileManager testee = $$$();

    Iterable<? extends JavaFileObject> result = testee.getJavaFileObjectsFromPaths(paths);
    return result;
  }

  private StandardJavaFileManager $$$()
  {
    return null;
  }
}
