package whatisnewin.javax.xml.parsers;

import javax.xml.parsers.DocumentBuilderFactory;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link DocumentBuilderFactory}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link DocumentBuilderFactory} is an old class but has new fields, constructors or methods.
 * @since 1.4
 * @see DocumentBuilderFactory
 */
public final class WhatIsNewInDocumentBuilderFactory
{
  /**
   * Example call to new method {@link DocumentBuilderFactory#newDefaultNSInstance()}.
   * @since 13
   * @see DocumentBuilderFactory#newDefaultNSInstance()
   */
  public static DocumentBuilderFactory newDefaultNSInstance()
  {
    DocumentBuilderFactory result = DocumentBuilderFactory.newDefaultNSInstance();
    return result;
  }

  /**
   * Example call to new method {@link DocumentBuilderFactory#newNSInstance()}.
   * @since 13
   * @see DocumentBuilderFactory#newNSInstance()
   */
  public static DocumentBuilderFactory newNSInstance()
  {
    DocumentBuilderFactory result = DocumentBuilderFactory.newNSInstance();
    return result;
  }

  /**
   * Example call to new method {@link DocumentBuilderFactory#newNSInstance(String, ClassLoader)}.
   * @since 13
   * @see DocumentBuilderFactory#newNSInstance(String, ClassLoader)
   */
  public static DocumentBuilderFactory newNSInstance(String factoryClassName, ClassLoader classLoader)
  {
    DocumentBuilderFactory result = DocumentBuilderFactory.newNSInstance(factoryClassName, classLoader);
    return result;
  }

}
