package whatisnewin.com.sun.source.util;

import com.sun.source.util.JavacTask;
import com.sun.source.util.ParameterNameProvider;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link JavacTask}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link JavacTask} is an old class but has new fields, constructors or methods
 * @since 1.6
 * @see JavacTask
 */
public final class WhatIsNewInJavacTask
{
  /**
   * Example call to new method {@link JavacTask#setParameterNameProvider}
   * @since 13
   * @see JavacTask#setParameterNameProvider
   */
  public void setParameterNameProvider(ParameterNameProvider provider)
  {
    JavacTask testee = $$$();

    testee.setParameterNameProvider(provider);
  }

  private JavacTask $$$()
  {
    return null;
  }
}
