package whatisnewin.javax.xml.crypto.dsig;

import javax.xml.crypto.dsig.CanonicalizationMethod;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link CanonicalizationMethod}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link CanonicalizationMethod} is an old class but has new fields, constructors or methods
 * @since 1.6
 * @see CanonicalizationMethod
 */
public final class WhatIsNewInCanonicalizationMethod
{
  /**
   * Example usage of the new field {@link CanonicalizationMethod#INCLUSIVE_11}
   * @since 13
   * @see CanonicalizationMethod#INCLUSIVE_11
   */
  public static  final String INCLUSIVE_11 = CanonicalizationMethod.INCLUSIVE_11;

  /**
   * Example usage of the new field {@link CanonicalizationMethod#INCLUSIVE_11_WITH_COMMENTS}
   * @since 13
   * @see CanonicalizationMethod#INCLUSIVE_11_WITH_COMMENTS
   */
  public static  final String INCLUSIVE_11_WITH_COMMENTS = CanonicalizationMethod.INCLUSIVE_11_WITH_COMMENTS;

}
