package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.Tree.Kind;

/**
 * This source file was generated by WhatIsNewInJava<br>
 *
 * This class provides an example call to each method in class {@link Kind}
 * that were newly introduced in Java versions 13.<br>
 *
 * {@link Kind} is an old class but has new fields, constructors or methods
 * @since UNDEFINED
 * @see Kind
 */
public final class WhatIsNewInTree$Kind
{
  /**
   * Example usage of the new field {@link Kind#YIELD}
   * @since 13
   * @see Kind#YIELD
   */
  public static  final Kind YIELD = Kind.YIELD;

}
