package whatisnewin.com.sun.source.tree;

import com.sun.source.tree.YieldTree;
import com.sun.source.tree.ExpressionTree;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link YieldTree}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link YieldTree} is a completely new class.
 * @since 13
 * @see YieldTree
 */
public final class WhatIsNewInYieldTree
{
  /**
   * Example call to new method {@link YieldTree#getValue()}.
   * @since 13
   * @see YieldTree#getValue()
   */
  public ExpressionTree getValue()
  {
    YieldTree testee = $$$();

    ExpressionTree result = testee.getValue();
    return result;
  }

  private YieldTree $$$()
  {
    return null;
  }
}
