package whatisnewin.java.time.chrono;

import java.time.chrono.JapaneseEra;

/**
 * This source file was generated by WhatIsNewInJava.<br>
 *
 * This class provides an example call to each method in class {@link JapaneseEra}
 * that were newly introduced in Java version 13.<br>
 *
 * {@link JapaneseEra} is an old class but has new fields, constructors or methods.
 * @since 1.8
 * @see JapaneseEra
 */
public final class WhatIsNewInJapaneseEra
{
  /**
   * Example usage of the new field {@link JapaneseEra#REIWA}.
   * @since 13
   * @see JapaneseEra#REIWA
   */
  public static final JapaneseEra REIWA = JapaneseEra.REIWA;

}
